  
################################################################################
# Copyright (c) IBM Corporation 2020
################################################################################
---
collections:
  - ibm.ibm_zos_cics
